spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot-rest
    username: SCOTT
    password: tiger
    driver-class-name: com.mysql.jdbc.Driver
  data:
    rest:
      # Set the default location from all requests
      base-path: /api
      # Set default page size when client didn't request specific page sizes
      default-page-size: 10
      max-page-size: 10

server:
  port: 8081