spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot-rest
    username: SCOTT
    password: tiger
    driver-class-name: com.mysql.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: create
    h2:
      console:
        enabled: false
      path: /console
    devtools:
      livereload:
        enabled: true

server:
  port: 8081